## ???????????? ????????? ?????? (Data source)
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/fullstack_db
#spring.datasource.username=postgres
#spring.datasource.password=123t456
#
## ???????????? ?????? Hibernate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.show_sql=true
#
## PUT, PATCH, DELETE
#spring.mvc.hiddenmethod.filter.enabled=true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fullstack_db
    username: postgres
    password: 123t456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    cors:
      allowed-origins: http://localhost:4200/